### ISSUE TITLE
Exercise 3 in lecture08-exercise-solutions.md

### ISSUE THREAD

**Issue by jdegrave** [uagc-it-readiness/backend-dev-nodejs#2]
@BrennaBlackwell @johnstonbl01 

So, as I was updating my file for Exercise 03 (authList function) with the solution posted in lecture08-exercise-solutions.md, I discovered an error in this line:

`if (arr[i][j].charCodeAt(0) < 97 || arr[i][j].charCodeAt(0) > 122) {
        validChars = false;
      }`

if you run it as-is, it always comes up false because the numbers are less than char code 97. 
Here's a possible fix, if you want to update the code: 

 if ((arr[i][j].charCodeAt(0) < 97 || arr[i][j].charCodeAt(0) > 122) **&& validNumber === false** ) {
            validChars = false;
          }

Not sure how to do a pull request on this, so decided to try out the "Issues" feature. Thanks!

**Comment by johnstonbl01** [comment]
Fixed! Thanks for letting us know!
